# Generated by Django 4.0.2 on 2022-02-11 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='season', max_length=64, verbose_name='Name')),
                ('start', models.DateField(default=django.utils.timezone.now, verbose_name='StarDate')),
                ('end', models.DateField(default=django.utils.timezone.now, verbose_name='EndDate')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
