# Generated by Django 4.0.2 on 2022-02-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_season_send_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='content_email',
            field=models.TextField(default='content email', verbose_name='content email'),
        ),
        migrations.AddField(
            model_name='season',
            name='title_email',
            field=models.CharField(default='title email', max_length=256, verbose_name='title email'),
        ),
    ]
